import 'package:flutter/foundation.dart';
import 'package:nutq/core/domain/content_language.dart';

/// A video's subtitles in one language, and what is known about the video.
@immutable
class VideoSubtitles {
  const VideoSubtitles({
    required this.title,
    required this.lines,
    required this.autoGenerated,
    this.duration,
  });

  final String title;
  final Duration? duration;

  /// The subtitle text, one caption per entry, cleaned of annotations.
  final List<String> lines;

  /// YouTube's speech recognition rather than subtitles a person wrote.
  final bool autoGenerated;
}

/// Reads a video's subtitles instead of its audio: no download and no speech
/// recognition, so even a long video is ready to summarize in seconds.
abstract interface class SubtitleProvider {
  /// Whether [link] names a video this provider can read.
  bool recognizes(String link);

  /// Subtitles in [language], preferring ones a person wrote. Throws
  /// [NoSubtitlesException] when the video has none in that language and
  /// [VideoUnavailableException] when the video cannot be reached.
  Future<VideoSubtitles> fetch(String link, ContentLanguage language);
}

class NoSubtitlesException implements Exception {
  const NoSubtitlesException(this.available);

  /// Language codes the video does have subtitles in.
  final List<String> available;

  @override
  String toString() => 'NoSubtitlesException(available: $available)';
}

class VideoUnavailableException implements Exception {
  const VideoUnavailableException(this.message);

  final String message;

  @override
  String toString() => 'VideoUnavailableException: $message';
}
