import 'package:nutq/features/jobs/domain/entities/job_failure.dart';
import 'package:nutq/features/jobs/domain/entities/job_progress.dart';
import 'package:nutq/features/jobs/domain/entities/job_source_type.dart';
import 'package:nutq/features/jobs/domain/entities/job_stage.dart';
import 'package:nutq/features/jobs/domain/entities/source_info.dart';
import 'package:nutq/features/jobs/domain/entities/source_transcript.dart';
import 'package:nutq/features/jobs/domain/services/video_subtitles.dart';
import 'package:nutq/features/jobs/domain/sources/transcript_source.dart';

/// A YouTube video, read through its subtitles in the job's language.
class YouTubeTranscriptSource implements TranscriptSource {
  const YouTubeTranscriptSource(this._subtitles);

  final SubtitleProvider _subtitles;

  @override
  JobSourceType get type => JobSourceType.youtube;

  /// Fetching subtitles takes seconds; the summary is the work.
  @override
  double get progressShare => 0.05;

  @override
  bool get transcribesAudio => false;

  @override
  Future<SourceTranscript> resolve(SourceRequest request) async {
    final link = request.job.sourceUrl ?? '';
    request.onProgress(const JobProgress(JobStage.acquiring, fraction: 0));
    final VideoSubtitles subtitles;
    try {
      subtitles = await _subtitles.fetch(link, request.job.sourceLanguage);
    } on NoSubtitlesException catch (e) {
      throw JobFailure(JobFailureKind.noSubtitles, 'available: ${e.available}');
    } on VideoUnavailableException catch (e) {
      throw JobFailure(JobFailureKind.sourceUnavailable, e.message);
    }
    request.cancellation.throwIfCancelled();
    await request.saveSourceInfo(
      SourceInfo(
        title: subtitles.title,
        durationSeconds: subtitles.duration == null
            ? null
            : subtitles.duration!.inMilliseconds / 1000,
      ),
    );
    request.onProgress(const JobProgress(JobStage.acquiring, fraction: 1));
    final text = subtitles.lines.join('\n');
    request.onPartialTranscript(text);
    return SourceTranscript(
      text,
      modelName: subtitles.autoGenerated ? 'youtube-auto-captions' : 'youtube-captions',
    );
  }
}
