import 'package:flutter_test/flutter_test.dart';
import 'package:nutq/core/domain/cancellation.dart';
import 'package:nutq/core/domain/content_language.dart';
import 'package:nutq/features/jobs/data/youtube/youtube_subtitle_provider.dart';
import 'package:nutq/features/jobs/domain/entities/job_detail_entity.dart';
import 'package:nutq/features/jobs/domain/entities/job_failure.dart';
import 'package:nutq/features/jobs/domain/entities/job_run_status.dart';
import 'package:nutq/features/jobs/domain/entities/job_source_type.dart';
import 'package:nutq/features/jobs/domain/entities/source_info.dart';
import 'package:nutq/features/jobs/domain/services/video_subtitles.dart';
import 'package:nutq/features/jobs/domain/sources/transcript_source.dart';
import 'package:nutq/features/jobs/domain/sources/youtube_transcript_source.dart';
import 'package:nutq/features/summarization/domain/entities/summary_length.dart';

class _Subtitles implements SubtitleProvider {
  _Subtitles({this.result, this.error});

  final VideoSubtitles? result;
  final Object? error;
  ContentLanguage? asked;

  @override
  bool recognizes(String link) => true;

  @override
  Future<VideoSubtitles> fetch(String link, ContentLanguage language) async {
    asked = language;
    // A test double that throws whatever the test scripted.
    // ignore: only_throw_errors
    if (error != null) throw error!;
    return result!;
  }
}

void main() {
  JobDetailEntity job({ContentLanguage language = ContentLanguage.ar}) => JobDetailEntity(
    id: 'j',
    status: JobRunStatus.running,
    sourceType: JobSourceType.youtube,
    sourceLanguage: language,
    summaryLanguage: language,
    requestedLength: SummaryLength.medium,
    createdAt: DateTime.utc(2026, 10),
    updatedAt: DateTime.utc(2026, 10),
    sourceUrl: 'https://youtu.be/abc12345678',
  );

  Future<(String, List<SourceInfo>, List<String>)> resolve(
    SubtitleProvider subtitles, {
    ContentLanguage language = ContentLanguage.ar,
  }) async {
    final saved = <SourceInfo>[];
    final partials = <String>[];
    final result = await YouTubeTranscriptSource(subtitles).resolve(
      SourceRequest(
        job: job(language: language),
        onProgress: (_) {},
        cancellation: CancellationToken(),
        saveSourceInfo: (info) async => saved.add(info),
        onPartialTranscript: partials.add,
      ),
    );
    return (result.text, saved, partials);
  }

  Future<JobFailureKind> failureOf(Future<Object?> future) async {
    try {
      await future;
    } on JobFailure catch (f) {
      return f.kind;
    }
    fail('expected a JobFailure');
  }

  test('reads the subtitles in the job language and records the title and length', () async {
    final subtitles = _Subtitles(
      result: const VideoSubtitles(
        title: 'محاضرة',
        lines: ['السطر الأول', 'السطر الثاني'],
        autoGenerated: false,
        duration: Duration(minutes: 5),
      ),
    );
    final (text, saved, partials) = await resolve(subtitles, language: ContentLanguage.en);
    expect(subtitles.asked, ContentLanguage.en);
    expect(text, 'السطر الأول\nالسطر الثاني');
    expect(saved.single.title, 'محاضرة');
    expect(saved.single.durationSeconds, 300);
    expect(partials, [text], reason: 'the transcript shows at once');
  });

  test('is not speech recognition, so its duration does not drive the estimate', () {
    expect(YouTubeTranscriptSource(_Subtitles()).transcribesAudio, isFalse);
  });

  test('no subtitles in that language and an unreachable video fail with their reasons', () async {
    expect(
      await failureOf(resolve(_Subtitles(error: const NoSubtitlesException(['en'])))),
      JobFailureKind.noSubtitles,
    );
    expect(
      await failureOf(resolve(_Subtitles(error: const VideoUnavailableException('offline')))),
      JobFailureKind.sourceUnavailable,
    );
  });

  group('YouTubeSubtitleProvider', () {
    final provider = YouTubeSubtitleProvider();

    test('recognizes the usual YouTube link shapes and nothing else', () {
      for (final link in [
        'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
        'https://youtu.be/dQw4w9WgXcQ?t=42',
        'https://www.youtube.com/shorts/dQw4w9WgXcQ',
        'https://m.youtube.com/watch?v=dQw4w9WgXcQ&feature=share',
        '  https://youtu.be/dQw4w9WgXcQ  ',
      ]) {
        expect(provider.recognizes(link), isTrue, reason: link);
      }
      for (final link in ['', 'https://vimeo.com/123', 'hello', 'https://youtube.com/']) {
        expect(provider.recognizes(link), isFalse, reason: link);
      }
    });

    test('cleans captions: annotations, spacing, empties and rolling repeats', () {
      expect(
        cleanCaptions([
          '[Music]',
          '♪♪ ♪',
          'مرحبا   بكم',
          'مرحبا بكم',
          'في  النشرة (موسيقى)',
          'النشرة', // already the end of the line before
          '',
          'والآن الأخبار',
        ]),
        ['مرحبا بكم', 'في النشرة', 'والآن الأخبار'],
      );
    });
  });
}
