import 'dart:io';

import 'package:nutq/core/domain/content_language.dart';
import 'package:nutq/features/jobs/domain/services/video_subtitles.dart';
import 'package:youtube_explode_dart/youtube_explode_dart.dart'
    show VideoId, YoutubeExplode, YoutubeExplodeException;

/// YouTube subtitles through `youtube_explode_dart`. The official Data API
/// only gives captions to a video's owner, so there is no sanctioned way to
/// read them; this reads what the YouTube apps read.
class YouTubeSubtitleProvider implements SubtitleProvider {
  YouTubeSubtitleProvider({YoutubeExplode Function()? client})
    : _client = client ?? YoutubeExplode.new;

  final YoutubeExplode Function() _client;

  @override
  bool recognizes(String link) => VideoId.parseVideoId(link.trim()) != null;

  @override
  Future<VideoSubtitles> fetch(String link, ContentLanguage language) async {
    final id = VideoId.parseVideoId(link.trim());
    if (id == null) throw VideoUnavailableException('not a YouTube link: $link');
    final yt = _client();
    try {
      final video = await yt.videos.get(id);
      final manifest = await yt.videos.closedCaptions.getManifest(id);
      final tracks = manifest.getByLanguage(language.code, autoGenerated: true)
        // A person's subtitles first; the same track comes in several formats.
        ..sort((a, b) => (a.isAutoGenerated ? 1 : 0).compareTo(b.isAutoGenerated ? 1 : 0));
      if (tracks.isEmpty) {
        throw NoSubtitlesException(manifest.tracks.map((t) => t.language.code).toSet().toList());
      }
      final track = await yt.videos.closedCaptions.get(tracks.first);
      return VideoSubtitles(
        title: video.title,
        duration: video.duration,
        lines: cleanCaptions([for (final c in track.captions) c.text]),
        autoGenerated: tracks.first.isAutoGenerated,
      );
    } on NoSubtitlesException {
      rethrow;
    } on VideoUnavailableException {
      rethrow;
    } on SocketException catch (e) {
      throw VideoUnavailableException('offline: ${e.message}');
    } on YoutubeExplodeException catch (e) {
      throw VideoUnavailableException(e.message);
    } finally {
      yt.close();
    }
  }
}

final _annotation = RegExp(
  r'\[[^\]]*\]|\([^)]*(music|applause|laughter|موسيقى|تصفيق|ضحك)[^)]*\)|♪+',
  caseSensitive: false,
);
final _spaces = RegExp(r'\s+');

/// Caption text as transcript lines: sound annotations (`[Music]`, `♪`)
/// removed, whitespace collapsed, empty lines dropped, and a line that only
/// repeats the one before dropped (auto-generated captions roll, so the same
/// words often appear twice in a row).
List<String> cleanCaptions(Iterable<String> captions) {
  final lines = <String>[];
  for (final caption in captions) {
    final text = caption.replaceAll(_annotation, ' ').replaceAll(_spaces, ' ').trim();
    if (text.isEmpty) continue;
    if (lines.isNotEmpty && (lines.last == text || lines.last.endsWith(text))) continue;
    lines.add(text);
  }
  return lines;
}
